### ISSUE TITLE
PID Source code

### ISSUE THREAD

**Issue by bcomnes** [jrleeman/TGE#125]
Super happy to see the lab I helped write evolve into other classrooms 👍  
🤞 I hope it worked well

In case it's helpful, the source code and raw materials can be found at https://github.com/bcomnes/315-lab-microcontroller 

and a few others from that year https://github.com/bcomnes?utf8=%E2%9C%93&tab=repositories&q=lab&type=source&language=

**Comment by jrleeman** [comment]
Thanks Bret! It was indeed very helpful! I'll use this issue as a reminder to add a link to your git repo as well. If you're ever in the Boulder area, I owe you a 🍺 !
