### ISSUE TITLE
Add safety precautions for EDM?

### ISSUE THREAD

**Issue by mtb-za** [jrleeman/TGE#47]
Just noticed the lack of an explicit `safety precautions` section like the other machines and tools had. Should one be added for completeness?

I find it hard to imagine that there are none needed!

**Comment by jrleeman** [comment]
The main hazards that come to mind are shock hazard and slip hazard from the dielectric oil Can you think of any others?

**Comment by mtb-za** [comment]
No idea! This is the first time I have heard of the technique, so you would know better than I. It was just noticeable that that section was missing here, but was present for everything else.
