### ISSUE TITLE
Electronic tools?

### ISSUE THREAD

**Issue by mtb-za** [jrleeman/TGE#49]
You go over the shop tools nicely (I learned some interesting stuff just reading through it).

Are you are planning to cover electronics tools as well: soldering irons, multimeters &c?

**Comment by jrleeman** [comment]
Yes, absolutely - They will be covered in a section on electronics prototyping. I'm hoping to keep the content about 2 weeks ahead of the lectures. Any PR's greatly appreciated ;)
