### ISSUE TITLE
Lab Exercise: Arduino Stoplight

### ISSUE THREAD

**Issue by kerryryan** [jrleeman/TGE#76]
On the Arduino Stoplight lab exercise page, the resistor colors specified under the 'Materials Section' for the 330 ohm and 10K ohm resistors are incorrect. The 330 ohm is listed as brown-black-brown and the 10K ohm as red-red-red. I think they should be orange-orange-brown and brown-black-orange, respectively.

**Comment by jrleeman** [comment]
Fixed in #78
